### ISSUE TITLE
How do you implement the generated adversarial image must be inside the epsilon-ball in l_inf  attack?

### ISSUE THREAD

**Issue by machanic** [snu-mllab/parsimonious-blackbox-attack#1]
I cannot find the code where the generated adversarial image must be resided inside epsilon-ball.
How do you implement that?

**Comment by symoon11** [comment]
We first initialize an adversarial noise as below
https://github.com/snu-mllab/parsimonious-blackbox-attack/blob/71b4a16e03b2c338e016b9296ce7ac4f690d1a0e/cifar10/attacks/parsimonious_attack.py#L95

and, we only flip the sign of the noise during the algorithm.
https://github.com/snu-mllab/parsimonious-blackbox-attack/blob/71b4a16e03b2c338e016b9296ce7ac4f690d1a0e/cifar10/attacks/local_search_helper.py#L77

So, the \ell_p norm of the noise is less or equal to \epsilon.
