### ISSUE TITLE
Why use another batch in local_search_helper.py?

### ISSUE THREAD

**Issue by Daizy97** [snu-mllab/parsimonious-blackbox-attack#4]
Wonderful code! I have a small question that why another batch is used in local_search_helper.py:
![image](https://user-images.githubusercontent.com/30400618/104933504-f5ba2f00-59e3-11eb-9fe3-cacc189adde7.png)
It seems this isn't mentioned in the paper. Is this for not making priority_queue too big that too many queries will be needed for local search on one batch?

**Comment by dssrgu** [comment]
Thank you for your interest in our work!

Yes, the batch in local_search_helper.py is used to reduce excessive queries for building a large priority queue, as many images only require few steps of local search.

**Comment by Daizy97** [comment]
Got it. Thanks very much for your response!
