### ISSUE TITLE
Does parismonious attack support attacking many images (a mini-batch of images) at the same time?

### ISSUE THREAD

**Issue by machanic** [snu-mllab/parsimonious-blackbox-attack#5]
I check your code, it seems that this code only support attack a single image, and if I have 1000 images in total. I have to attack them one by one, this is slow.
Does the code support attacking a mini-batch of images at the same time?

**Comment by symoon11** [comment]
The current version of the code only supports attacking a single image, since the greedy addition and deletion in the local search algorithm cannot benefit from parallelization. Some part of the code can be parallelized, but there is no tentative plan to update the code.
